const FLOOR_PLAN_ROOMS = [
  { x: 0, y: 0, w: 120, h: 80, accent: false },
  { x: 120, y: 0, w: 80, h: 80, accent: false },
  { x: 200, y: 0, w: 100, h: 80, accent: true },
  { x: 0, y: 80, w: 180, h: 120, accent: false },
  { x: 180, y: 80, w: 120, h: 120, accent: false },
  { x: 0, y: 200, w: 150, h: 100, accent: false },
  { x: 150, y: 200, w: 150, h: 100, accent: false },
  { x: 0, y: 300, w: 150, h: 100, accent: false },
  { x: 150, y: 300, w: 150, h: 100, accent: false },
]

function FloorPlanTile() {
  return (
    <div className="relative col-span-2 row-span-2 overflow-hidden rounded-sm border border-white/10 bg-[#1e2126] p-4">
      <svg viewBox="0 0 300 400" className="h-[calc(100%-1.75rem)] w-full" role="img" aria-label="Illustrative floor plan generated by Griha">
        {FLOOR_PLAN_ROOMS.map((room, i) => (
          <rect
            key={i}
            x={room.x}
            y={room.y}
            width={room.w}
            height={room.h}
            fill={room.accent ? '#e0a94a33' : '#ffffff0d'}
            stroke={room.accent ? '#e0a94a' : '#ffffff33'}
            strokeWidth={2}
          />
        ))}
      </svg>
      <p className="mt-2 text-xs font-medium text-white/90">3BHK · North-facing · 30×40 plot</p>
      <p className="text-[11px] text-white/50">Auto-dimensioned 2D floor plan</p>
    </div>
  )
}

function StatTile() {
  return (
    <div className="col-span-2 flex flex-col justify-center rounded-sm border border-white/10 bg-[#1e2126] p-4">
      <p className="font-display text-3xl font-bold text-[#e0a94a] tabular-nums">12,000+</p>
      <p className="mt-1 text-xs text-white/60">floor plans generated across India</p>
    </div>
  )
}

function CompassTile() {
  return (
    <div className="col-span-2 flex items-center gap-3 rounded-sm border border-white/10 bg-[#1e2126] p-4">
      <svg viewBox="0 0 44 44" className="size-9 shrink-0" role="img" aria-label="Compass showing north">
        <circle cx="22" cy="22" r="19" fill="none" stroke="#ffffff33" strokeWidth="1.5" />
        <line x1="22" y1="22" x2="22" y2="6" stroke="#e0a94a" strokeWidth="2" />
        <line x1="22" y1="6" x2="17" y2="14" stroke="#e0a94a" strokeWidth="2" />
        <line x1="22" y1="6" x2="27" y2="14" stroke="#e0a94a" strokeWidth="2" />
        <text x="22" y="36" textAnchor="middle" fontSize="9" fontWeight="700" fill="#ffffff90">
          N
        </text>
      </svg>
      <p className="text-xs text-white/70">Every layout checked against Vastu Shastra</p>
    </div>
  )
}

function IsometricRoomTile() {
  return (
    <div className="col-span-2 flex items-center gap-3 rounded-sm border border-white/10 bg-[#1e2126] p-4">
      <svg viewBox="0 0 100 100" className="size-12 shrink-0" role="img" aria-label="Isometric illustration of a 3D room massing">
        <polygon points="50,8 88,29 50,50 12,29" fill="#3a3d43" />
        <polygon points="12,29 50,50 50,92 12,71" fill="#24272c" />
        <polygon points="88,29 50,50 50,92 88,71" fill="#2e3136" />
      </svg>
      <p className="text-xs text-white/70">Photoreal 3D walkthroughs, generated instantly</p>
    </div>
  )
}

function TestimonialTile() {
  return (
    <div className="col-span-2 flex flex-col justify-center rounded-sm border border-white/10 bg-[#1e2126] p-4">
      <p className="text-xs leading-relaxed text-white/80">
        "The AI understood our need for a north-east pooja room instantly."
      </p>
      <p className="mt-1.5 text-[11px] text-white/50">— Priya R., Bengaluru</p>
    </div>
  )
}

export function AuthShowcase({ className }: { className?: string }) {
  return (
    <div className={className} style={{ background: '#14161a' }}>
      <div className="flex h-full flex-col p-10">
        <div>
          <div className="flex items-center gap-2.5">
            <span className="font-display text-lg font-semibold text-white">Griha</span>
          </div>
          <p className="mt-4 max-w-sm font-display text-2xl leading-snug font-semibold text-white">
            AI-powered home design, built for Indian families
          </p>
        </div>

        <div className="mt-8 grid flex-1 grid-cols-4 grid-rows-3 gap-3">
          <FloorPlanTile />
          <StatTile />
          <CompassTile />
          <IsometricRoomTile />
          <TestimonialTile />
        </div>

        <p className="mt-6 text-[11px] text-white/40">
          Vastu-reviewed · Room-wise BOQ included · Exports to AutoCAD, Revit &amp; SolidWorks
        </p>
      </div>
    </div>
  )
}
